### ISSUE TITLE
Feature request: Support for CKEditor 4.5.0

### ISSUE THREAD

**Issue by TimeLord2004** [OpenESignForms/vaadin-ckeditor#45]
Is there a plan to support CKEditor 4.5.0 (currently in beta)? 4.5.0 looks like a big upgrade.
We really want that because it includes 'Image upload widget was introduced to upload dropped images', a feature we _really_ need.

Apparently:
"there are no current plans to deal with image upload widget specifically.  Anything that can be done out of the box with CKEditor and its use in Vaadin we'll shoot for, but file uploads typically require a server-side component to accept the uploaded file, etc."
[I guess I'd envisage "a server-side component to accept the uploaded file" to be similar to an editor save event? Or maybe that is over simplistic...]

If not, is there any way we could integrate http://ckeditor.com/addon/simpleuploads into the existing vaadin-ckeditor? Will that even work without rebuilding vaadin-ckeditor in some way?

Or is there a way to reduce vaadin-ckeditor to be more of a wrapper for whatever version of CKEditor we choose?

Thanks

**Comment by TimeLord2004** [comment]
Hi, it seems we misunderstood the capabilities of the current CKEditor. We thought it wasn't possible to cut'n'paste an image into the editor (or drag an image into it from the desktop), but this already works in 4.4.7. The image is embedded in the html as a data url (uuencoded), which is fine for us - we don't need the server side to handle the images if the user has embedded them directly in the html... Problem solved. :-)

**Comment by OpenESignForms** [comment]
We noted that only appears to work for Firefox, but if you are good, so are we!
