### ISSUE TITLE
Get selected html , is it possible ?

### ISSUE THREAD

**Issue by ado2000** [OpenESignForms/vaadin-ckeditor#46]
Hi, 
compliments for the plugin.

is it possible to get selected html ?

Thanks

**Comment by OpenESignForms** [comment]
Not now. Does CKEditor have a method to be notified when HTML is selected and then retrieve the selected HTML?

**Comment by ado2000** [comment]
Hi,
This code seams run correctly on my safari.

you can register a selectionChange event and get the html content.

Hope can help to release e new version of this useful plugin

may be i can help.

Thanks.

CKEDITOR.instances.editor1.on( 'selectionChange', function( evt ) {
    
    alert( getSelectionHtml(CKEDITOR.instances.editor1)) ;

} );

function getSelectionHtml(editor) {
    var sel = editor.getSelection();
    var ranges = sel.getRanges();
    var el = new CKEDITOR.dom.element("div");
    for (var i = 0, len = ranges.length; i < len; ++i) {
        el.append(ranges[i].cloneContents());
    }
    return el.getHtml();
}

**Comment by OpenESignForms** [comment]
That's useful. We'll have to see what it would mean to enable that so if you register a new selection listener with the Vaadin editor object (like you can a value change listener), we'd send along such events.  It may not be hard to do, likely mirroring how editor changes are sent along, but we do find there are always issues based on whether ckeditor fires those events in SOURCE mode too, etc.  

Is it enough to have the selected HTML without knowing where in the full HTML that is?

**Comment by ado2000** [comment]
This function retrieve the html that is selected, for me it is enough , what i need is to get the html and check if an image is selected so instead of insert the complete img html tag i need to substitute only the image path

Do you think could be released soon a beta version ?
I could also help, but I'm not so practice with ivy and eclipse, i work with maven and netbeans.
Thanks

**Comment by OpenESignForms** [comment]
We are giving this a try, but it seems quite unreliable, and often we don't see it firing unless we also blur the editor.  I'm not sure if this ticket is proof that it's not reliable or there is something else we need to do:

https://dev.ckeditor.com/ticket/6443

If you are interested, we could share our dev JAR (not sure how files are shared on github, but if you send an email to yozons AT gmail asking for it, we can reply back with it).

Anyway, we find that selecting a full element seems to work better than if we select just a word in a paragraph.  We have a javascript console log in the getSelectedHtml() method that is called whenever the 'selectionChange' event fires in the editor and it doesn't seem to show reliably what I've just selected (and sometimes seems to show my prior selection that didn't seem to fire an event at all).

At any rate, it's currently too unreliable to release as it is now.

**Comment by ado2000** [comment]
Hi,

Thank you for the try.
really the selection change only selecting a new paragraph that is strange!!
Anyway, for my needs it is enough, because i will use it only on selection of images.
can you share the source too ?
I'll write to your private email.

thanks

**Comment by OpenESignForms** [comment]
Yeah, give it a try.  We just went ahead and checked it in and pushed it to the repository.  That way you'll have the code and our JAR.  Do remember to recompile widgetsets to use this new JAR.  With any luck, perhaps you can track down if it's us, Vaadin or CKEditor that's the issue.  It seems like CKEditor is not being reliable from here, though.  This pre-release is called 7.10.0_pre0626.

**Comment by ado2000** [comment]
Thanks, i'll check it out.

**Comment by OpenESignForms** [comment]
We upgraded to CKEditor 4.5.1 and used the this.getSelectedHtml(true) option and it seems to work no better, per se.  You can give it a try if you want.  The official 7.10.0 release of the component has been put into the Vaadin directory, and of course git is also updated with the latest code.  Like before, you'll need to enable the selected html listener on your editor to make use of it.

**Comment by ado2000** [comment]
Hi, thanks for your good work, also i  was checking the 4.5.1 version.
The problem on the onSelectionChange event of ckeditor is that it is not raised on every change as the documentation says.

"Fired when selection inside editor has been changed. Note that this event is fired only when selection's start element (container of a selecion start) changes, not on every possible selection change. Thanks to that selectionChange is fired less frequently, but on every context (the elements path holding selection's start) change."

So what we need is to call the this.getSelectedHtml(true) as we need and not getting the value after the onSelectionChange is raised.

I do not know very well the vaadin module development to know if it is possible to call a server Method that retrieve a value from the client side.

What do you think ?

**Comment by ado2000** [comment]
May be we can use something like this https://jsfiddle.net/Lfkr5zo0/8/ to sent to the server the selected html so without use the onSelectionChange.

```javascript
function logSelection() {        
    if(this.getSelectedHtml(true).length > 0){    
        console.log( this.getSelectedHtml(true) );
    }
}

CKEDITOR.replace( 'editor', {
    on: {
        contentDom: function() {
            this.document.on( 'mouseup', logSelection, this );
            this.document.on( 'keyup', logSelection, this );
        }
    }
} );
```

The only things to consider are the performance, but if we send to the server only when the length of the selection is grater than 0 should be ok

**Comment by OpenESignForms** [comment]
Give this is a try with the 7.10.1 version.  It does seem to work much better.  While I was concerned about the mouseup and keyup events, I don't see any real performance issues (yet).  Give it a try and see if it's working for you or you see any performance issues.  I won't general release this version until it seems ready.  In general, unless you register a selection change listener, and that listener detects selected text, nothing is sent to the server, so any performance issues should really just be in the browser (unless there's a bug in our code <smile>).

**Comment by ado2000** [comment]
hi,

it seems run correctly , the only thing is that when the selection is removed should rise an event to reset the selection.

may be you can check when is the first time the selection is empty and send the event.

Bye

**Comment by OpenESignForms** [comment]
Sure, "if I give a mouse a cookie..." keeps on adding requirements <smile>  We've checked in the 7.10.2 version and this should resolve this issue.  There's a helper function in the event that will tell you if you have selected text or not:

		ckEditorTextField.addSelectionChangeListener(new SelectionChangeListener() {
			public void selectionChange(SelectionChangeEvent event) {
				if ( event.hasSelectedHtml() ) {
					Notification.show("CKEditor selected HTML: " + event.getSelectedHtml(), Type.ERROR_MESSAGE);
					ckEditorTextField1.focus();
				} else {
					Notification.show("CKEditor un-select reported", Type.ERROR_MESSAGE);
				}
			}
		});

**Comment by ado2000** [comment]
Good job, it seems run well
Thanks
