### ISSUE TITLE
Image drag'n'drop

### ISSUE THREAD

**Issue by yoursnowyfriendleo** [OpenESignForms/vaadin-ckeditor#47]
Drag'n'drop (copy'n'paste) an image into the editor is working in Firefox, but NOT in any other browser. Any plans to add this functionality in ckeditor? Or is there any other way to 'drop' image inside editor?

Thanks

**Comment by OpenESignForms** [comment]
For CKEditor questions, you'll need to go to their project site.  We just have a wrapper that essentially sets/gets the HTML and have nothing to do with CKEditor functionality itself.  I was impressed it worked on FF, noting that it uses data urls to embed the image directly in the HTML versus the traditional reference to an image file on the server.

**Comment by yoursnowyfriendleo** [comment]
I will go to their project page. Thank you.
