### ISSUE TITLE
How to implement on paste event on CKEditor ?

### ISSUE THREAD

**Issue by dmarko484** [OpenESignForms/vaadin-ckeditor#49]
In our legacy code we bind 'paste' event on ckeditor as on example below. How we can bind such event using VAADIn Ckeditor plugin? (btw. thanks for excellent plugin !!)

```
var editor = CKEDITOR.instances["id"]
editor.on('paste', function (evt) {
        // some code goes here       
 });
```

**Comment by OpenESignForms** [comment]
Does the onChange not work?  Seems like a paste would trigger a change event, too.  Currently, you can do this by mirroring the code for other ckeditor events and registering listeners, etc.

**Comment by dmarko484** [comment]
Its for image paste plugin, when user can paste image from clipboard and this event handles such behaviour so it must be client (browser) side

**Comment by OpenESignForms** [comment]
So when you do an image paste via that plugin, ckeditor doesn't also fire a change event?  Seems like a pasted image would change the editor contents.

**Comment by dmarko484** [comment]
pasted image is saved to our app and paste event creates <img /> url to server

**Comment by OpenESignForms** [comment]
Closing this for lack of follow-up from original issue, nor any proposed solutions.  It seems any change event that's not firing on changes to the editor are a bug in the ckeditor over which we have no control.
