### ISSUE TITLE
How to grow CKEditor window?

### ISSUE THREAD

**Issue by dmarko484** [OpenESignForms/vaadin-ckeditor#50]
In our legacy app we were using 'autogrow' plugin for ckeditor. Its not working with Vaadin but whats more the problem is that user cannot event resize ckeditor window manualy. Making ckeditor verticaly bigger cant be done as it can be seen in official demo using the link below. Is there any fix or workaround for this?

[http://open.esignforms.com/Vaadin7CKEditor/](http://open.esignforms.com/Vaadin7CKEditor/)

**Comment by OpenESignForms** [comment]
If you look at the "open non-modal subwindow with 100% height" button, the editor will resize to fit the area.  'autogrow' plugin is different in that it will grow the page size to grow the editor window, but this allows as the browser window grows, the editor will too.

**Comment by OpenESignForms** [comment]
Closing for lack of follow-up issues to resolve.
