### ISSUE TITLE
CKEditorConfig.addExtraConfig is producing a javascript error

### ISSUE THREAD

**Issue by tarekmamdouh** [OpenESignForms/vaadin-ckeditor#57]
I am trying to enable scayt by default so i added the following line 
`config.addExtraConfig("config.scayt_autoStartup", "true");`
However I keep getting a javascript error. 
convertJavaScriptStringToObject() INVALID JAVASCRIPT: { config.scayt_autoStartup : true }

I am aware it's a "hack" so can you please either fix it or add another way to configure the editor

**Comment by OpenESignForms** [comment]
Most likely you don't want the 'config.' in front and just something like:

config.addExtraConfig("scayt_autoStartup", "true");

**Comment by tarekmamdouh** [comment]
Thank you, this worked.
