### ISSUE TITLE
Documentation Request: own build with custom plugins

### ISSUE THREAD

**Issue by mheicke** [OpenESignForms/vaadin-ckeditor#58]
At the moment I'm trying to include my own custom build of your wrapper with an CKEditor download with custom Plugins (for example the placeholder, tag, Placeholder Select, Strinsert etc). I already checked out your project, copied the downloaded CKEditor code into the correct folder. My problem is: what to do next? I tried different solutions, but got stuck everywhere. Can you provide the steps until the newly build version is usable in a Vaadin project? I guess this could be beneficial to a lot of people.
Thank you in advance, Matt

PS: great work :)

**Comment by OpenESignForms** [comment]
I don't think anybody is up to a general doc task, but if you have the procedure and would like it documented, we can add it.

In general, you just put your plugins in the plugins folder for where you have installed your CKEditor javascript code.  In our system, that's under src/org/vaadin/openesignforms/ckeditor/widgetset/public/ckeditor/plugins   

When building yourself, you first need to put the CKEditor release in the folder just one up from there (this is not our code, but the CKEditor Javascript bundle of code): src/org/vaadin/openesignforms/ckeditor/widgetset/public/ckeditor 

You then can do a widgetset compilation per standard vaadin plugins to test out your ckeditor customized project.  We use the 'Export' option in Eclipse to choose 'Vaadin->Vaadin Add-on Package' to generate the JAR that we provide.

Assuming your project has the JAR, you can then enable the plugins via CKEditorConfig object with 'extraPlugins' option method: addToExtraPlugins(yourpluginname)

Note that if you release the add on JAR to another project, that project will also need to recompile the widgetset.

**Comment by mheicke** [comment]
Hey, thank you guys. This already helped me a lot. It somehow wasn't compiled in my CustomWidgetSet (which is done by maven in our setup), but I solved it by installing the jar into our local maven repository and linking it from there :) I also needed to copy the plugins used by your wrapper into the plugins folder to make it run (otherwise there was an obfuscated error message in the JS console), I guess you somewhere link those plugins and the CKEditor does not like it, if one of them is missing :)
