### ISSUE TITLE
Content area is editable in readonly mode

### ISSUE THREAD

**Issue by coolersport** [OpenESignForms/vaadin-ckeditor#64]
When setting the component to read only, the editor content area is still editable. This is because protectedBody flag is set to false which will set document.body.contentEditable to true regardless of readonly flag.

The solution should take into account readOnly flag when performing the update, e.g.:

    this.document.getBody().$.contentEditable = !readOnly && !protectBody;

**Comment by OpenESignForms** [comment]
Thank you for the suggested fix.

We didn't code the protectedBody feature that was added back in 2011.  We are not even sure what it does as we've never used it ourselves.  What does it mean as you clearly are calling the setProtectedBody(true) on the editor?

That is, should readOnly make assumptions about protectedBody as you suggest, or should those who call setReadOnly(false) [and who have also done setProtectedBody(true)] also just call call setProtectedBody(false).  Or are these two completely unrelated items?

Thanks for your help in understanding what the protected body means.

**Comment by OpenESignForms** [comment]
Forgot to close this as it was included in the 7.12.2 release.
