### ISSUE TITLE
CKEditor generates invalid css file url with double slashes, preventing it from loading the css file

### ISSUE THREAD

**Issue by rhaex** [OpenESignForms/vaadin-ckeditor#70]
When you open a page with the CKEditor Wrapper component on it, you will see the following INFO messages from Vaadin in the logs:

> INFO: Requested resource [/VAADIN/widgetsets/nl.abacus.pim.web.WebWidgetSet/ckeditor/plugins/tableselection//styles/tableselection.css] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.

Which correctly says it cannot load that css file, as the double slash is not valid.
http://localhost/VAADIN/widgetsets/someWidgetSet/ckeditor/plugins/tableselection//styles/tableselection.css results in a 404.

http://localhost/VAADIN/widgetsets/someWidgetSet/ckeditor/plugins/tableselection/styles/tableselection.css results in the correct css file.

The error seems to be in the _ckeditor.js_ file, in there is the piece of code: 
`CKEDITOR.document.appendStyleSheet(this.path+"/styles/tableselection.css")`

which prepends a slash to it, but this.path results in a path that already contains a trailing slash, resulting in this invalid URL.

I do not know the impact of this bug, but that css file must have a reason for being there.

**Comment by OpenESignForms** [comment]
You didn't mention what version you were running, but we don't see that in our logs at all.  Most likely it's been fixed.  We see this in our logs: 
[26/Oct/2017:01:30:52 -0700] "GET /Vaadin7CKEditor/VAADIN/widgetsets/org.vaadin.openesignforms.ckeditor.widgetset.VaadinCKEditorWidgetset/ckeditor/plugins/tableselection/styles/tableselection.css HTTP/1.1" 200

Regardless, you'd want to report such a bug to CKEditor as we don't modify any CKEditor code.

The latest version of our Vaadin plugin is 7.12.3 and it comes with CKEditor 4.7.3.
